import type { Stage } from './types';

// План работ заведён только для части объектов — остальные демонстрируют
// пустое состояние вкладки «План работ».
export const SEED_STAGES: Stage[] = [
  {
    id: 'stage-1',
    siteId: 's-1',
    name: 'Демонтаж старого оборудования участка №2',
    description: 'Демонтаж и вывоз выработавшего ресурс конвейерного оборудования.',
    startDate: '2026-07-01',
    endDate: '2026-07-20',
    status: 'done',
    assignee: 'Терехов Игорь Валерьевич',
    progress: 100,
    dependsOn: null,
    files: [{ id: 'stagefile-1', name: 'Акт_демонтажа.pdf', uploadedAt: '2026-07-20T10:00:00.000Z' }],
    requestIds: [],
  },
  {
    id: 'stage-2',
    siteId: 's-1',
    name: 'Монтаж кабельной линии КГЭШ',
    description: 'Прокладка и подключение силового кабеля на участке №2.',
    startDate: '2026-07-21',
    endDate: '2026-08-25',
    status: 'in_progress',
    assignee: 'Терехов Игорь Валерьевич',
    progress: 60,
    dependsOn: 'stage-1',
    files: [],
    requestIds: ['req-seed-1'],
  },
  {
    id: 'stage-3',
    siteId: 's-1',
    name: 'Пусконаладка электрооборудования',
    description: 'Проверка и настройка вновь смонтированного электрооборудования.',
    startDate: '2026-08-26',
    endDate: '2026-09-15',
    status: 'planned',
    assignee: 'Соколова Елена Викторовна',
    progress: 0,
    dependsOn: 'stage-2',
    files: [],
    requestIds: ['req-seed-2'],
  },
  {
    id: 'stage-4',
    siteId: 's-1',
    name: 'Обучение персонала работе с новым оборудованием',
    description: 'Инструктаж и обучение эксплуатационного персонала участка.',
    startDate: '2026-08-10',
    endDate: '2026-08-20',
    status: 'delayed',
    assignee: 'Терехов Игорь Валерьевич',
    progress: 20,
    dependsOn: null,
    files: [],
    requestIds: [],
  },
  {
    id: 'stage-5',
    siteId: 's-3',
    name: 'Геологоразведочные работы',
    description: 'Уточнение границ зон разработки на текущий период.',
    startDate: '2026-06-01',
    endDate: '2026-06-30',
    status: 'done',
    assignee: 'Симонова Анна Дмитриевна',
    progress: 100,
    dependsOn: null,
    files: [],
    requestIds: [],
  },
  {
    id: 'stage-6',
    siteId: 's-3',
    name: 'Вскрышные работы',
    description: 'Вскрытие рудного тела на новом горизонте.',
    startDate: '2026-07-01',
    endDate: '2026-09-01',
    status: 'in_progress',
    assignee: 'Симонова Анна Дмитриевна',
    progress: 45,
    dependsOn: 'stage-5',
    files: [{ id: 'stagefile-2', name: 'Маркшейдерская_съёмка.pdf', uploadedAt: '2026-08-01T09:00:00.000Z' }],
    requestIds: [],
  },
];
